stages:
- mirror-to-github

build:
    stage: mirror-to-github
    image: "ubuntu:22.04"
    variables:
        DESTINATION_GITHUB_REPOSITORY: git@github.com:vhurtevent/mirror-test.git 

    before_script:
    - apt-get update -y && apt-get install openssh-client -y
    - apt install git -y
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$GITHUB_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh    
    script:
    - git log
    - git push github --all
    - git push github --tags
    
    only:
    - branches
